tasks:
  - name: original
    params:
      model_path: /scratch/yl258/kp759/Unlearning/semantic-unlearning/outputs/finetuned_model_3B_instruct

  - name: corrupt
    params:
      model_path: /scratch/yl258/kp759/Unlearning/semantic-unlearning/outputs/finetuned_model_3B_instruct
      corrupt_method: rand_noise_first_n
      corrupt_args:
        dims:
          - 1
          - 3072
        strength:
          - 5
          - 50
          - 3072

  - name: corrupt
    params:
      model_path: /scratch/yl258/kp759/Unlearning/semantic-unlearning/outputs/finetuned_model_3B_instruct
      corrupt_method: rand_noise_rand_n
      corrupt_args:
        dims:
          - 1
        strength:
          - 5
          - 50
          - 3072

  - name: corrupt
    params:
      model_path: /scratch/yl258/kp759/Unlearning/semantic-unlearning/outputs/finetuned_model_3B_instruct
      corrupt_method: zero_out_top_k
      corrupt_args:
        dims:
          - 500
        strength:
          - null

  - name: corrupt
    params:
      model_path: /scratch/yl258/kp759/Unlearning/semantic-unlearning/outputs/finetuned_model_3B_instruct
      corrupt_method: flip_sign_top_k
      corrupt_args:
        dims:
          - 3072
        strength:
          - null
